# Minimum flashcards per collection
MIN_FLASHCARDS = 2

LANGUAGES = (
    "Afrikaans",
    "Albanian",
    "Arabic",
    "Armenian",
    "Azerbaijani",
    "Belarusian",
    "Bengali",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Finnish",
    "French",
    "Georgian",
    "German",
    "Greek",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Kongo",
    "Korean",
    "Kurdish",
    "Lao",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Moldavian",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Persian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Somali",
    "Spanish",
    "Swedish",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Vietnamese",
    "Zulu"
)

LANG_CHOICES = (
    ('afrikaans', 'Afrikaans'),
    ('albanian', 'Albanian'),
    ('arabic', 'Arabic'),
    ('armenian', 'Armenian'),
    ('azerbaijani', 'Azerbaijani'),
    ('belarusian', 'Belarusian'),
    ('bengali', 'Bengali'),
    ('bosnian', 'Bosnian'),
    ('bulgarian', 'Bulgarian'),
    ('catalan', 'Catalan'),
    ('chinese', 'Chinese'),
    ('croatian', 'Croatian'),
    ('czech', 'Czech'),
    ('danish', 'Danish'),
    ('dutch', 'Dutch'),
    ('english', 'English'),
    ('estonian', 'Estonian'),
    ('finnish', 'Finnish'),
    ('french', 'French'),
    ('georgian', 'Georgian'),
    ('german', 'German'),
    ('greek', 'Greek'),
    ('hindi', 'Hindi'),
    ('hungarian', 'Hungarian'),
    ('icelandic', 'Icelandic'),
    ('indonesian', 'Indonesian'),
    ('irish', 'Irish'),
    ('italian', 'Italian'),
    ('japanese', 'Japanese'),
    ('kongo', 'Kongo'),
    ('korean', 'Korean'),
    ('kurdish', 'Kurdish'),
    ('lao', 'Lao'),
    ('latin', 'Latin'),
    ('latvian', 'Latvian'),
    ('lithuanian', 'Lithuanian'),
    ('macedonian', 'Macedonian'),
    ('moldavian', 'Moldavian'),
    ('mongolian', 'Mongolian'),
    ('nepali', 'Nepali'),
    ('norwegian', 'Norwegian'),
    ('persian', 'Persian'),
    ('polish', 'Polish'),
    ('portuguese', 'Portuguese'),
    ('romanian', 'Romanian'),
    ('russian', 'Russian'),
    ('serbian', 'Serbian'),
    ('slovak', 'Slovak'),
    ('slovenian', 'Slovenian'),
    ('somali', 'Somali'),
    ('spanish', 'Spanish'),
    ('swedish', 'Swedish'),
    ('thai', 'Thai'),
    ('turkish', 'Turkish'),
    ('ukrainian', 'Ukrainian'),
    ('vietnamese', 'Vietnamese'),
    ('zulu', 'Zulu')
)
